# Site settings
name: Rishabh Saxena
title: Rishabh Saxena | Backend Software Engineer
description: Backend Software Engineer focused on building scalable and secure architectures
url: ""
baseurl: "srishabh.com"
email: contact@srishabh.com
cover: https://srishabh.com/img/og.png
logo: https://srishabh.com/img/emojis/technologist.png
resume: https://srishabh.com/resume.pdf
social:
  - title: email
    url: mailto:contact@srishabh.com
  - title: twitter
    url: https://twitter.com/equate_rs
  - title: facebook
    url: https://facebook.com/rishabhstr
  - title: instagram
    url: https://instagram.com/rishabhstr
  - title: medium
    url: https://medium.com/rishabhstr
  - title: github
    url: https://github.com/rishabhs95
  - title: linkedin
    url: https://www.linkedin.com/in/saxenarishabh

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
